/********************************************************************
* daughterparticleDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error daughterparticleDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledaughterparticleDict();
extern void G__cpp_setup_inheritancedaughterparticleDict();
extern void G__cpp_setup_typetabledaughterparticleDict();
extern void G__cpp_setup_memvardaughterparticleDict();
extern void G__cpp_setup_globaldaughterparticleDict();
extern void G__cpp_setup_memfuncdaughterparticleDict();
extern void G__cpp_setup_funcdaughterparticleDict();
extern void G__set_cpp_environmentdaughterparticleDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "daughterparticle.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__daughterparticleDictLN_TClass;
extern G__linked_taginfo G__daughterparticleDictLN_TBuffer;
extern G__linked_taginfo G__daughterparticleDictLN_TMemberInspector;
extern G__linked_taginfo G__daughterparticleDictLN_TObject;
extern G__linked_taginfo G__daughterparticleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__daughterparticleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__daughterparticleDictLN_daughterparticle;

/* STUB derived class for protected member access */
