/********************************************************************
* dmesonDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dmesonDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledmesonDict();
extern void G__cpp_setup_inheritancedmesonDict();
extern void G__cpp_setup_typetabledmesonDict();
extern void G__cpp_setup_memvardmesonDict();
extern void G__cpp_setup_globaldmesonDict();
extern void G__cpp_setup_memfuncdmesonDict();
extern void G__cpp_setup_funcdmesonDict();
extern void G__set_cpp_environmentdmesonDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "dmeson.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dmesonDictLN_TClass;
extern G__linked_taginfo G__dmesonDictLN_TBuffer;
extern G__linked_taginfo G__dmesonDictLN_TMemberInspector;
extern G__linked_taginfo G__dmesonDictLN_TObject;
extern G__linked_taginfo G__dmesonDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dmesonDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dmesonDictLN_dmeson;
extern G__linked_taginfo G__dmesonDictLN_vectorlEdaughterparticlecOallocatorlEdaughterparticlegRsPgR;
extern G__linked_taginfo G__dmesonDictLN_reverse_iteratorlEvectorlEdaughterparticlecOallocatorlEdaughterparticlegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dmesonDictLN_vectorlEmotherquarkcOallocatorlEmotherquarkgRsPgR;
extern G__linked_taginfo G__dmesonDictLN_reverse_iteratorlEvectorlEmotherquarkcOallocatorlEmotherquarkgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dmesonDictLN_vectorlEmiddleparticlecOallocatorlEmiddleparticlegRsPgR;
extern G__linked_taginfo G__dmesonDictLN_reverse_iteratorlEvectorlEmiddleparticlecOallocatorlEmiddleparticlegRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
