/********************************************************************
* middleparticleDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error middleparticleDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemiddleparticleDict();
extern void G__cpp_setup_inheritancemiddleparticleDict();
extern void G__cpp_setup_typetablemiddleparticleDict();
extern void G__cpp_setup_memvarmiddleparticleDict();
extern void G__cpp_setup_globalmiddleparticleDict();
extern void G__cpp_setup_memfuncmiddleparticleDict();
extern void G__cpp_setup_funcmiddleparticleDict();
extern void G__set_cpp_environmentmiddleparticleDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "middleparticle.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__middleparticleDictLN_TClass;
extern G__linked_taginfo G__middleparticleDictLN_TBuffer;
extern G__linked_taginfo G__middleparticleDictLN_TMemberInspector;
extern G__linked_taginfo G__middleparticleDictLN_TObject;
extern G__linked_taginfo G__middleparticleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__middleparticleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__middleparticleDictLN_middleparticle;

/* STUB derived class for protected member access */
