/********************************************************************
* motherquarkDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error motherquarkDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemotherquarkDict();
extern void G__cpp_setup_inheritancemotherquarkDict();
extern void G__cpp_setup_typetablemotherquarkDict();
extern void G__cpp_setup_memvarmotherquarkDict();
extern void G__cpp_setup_globalmotherquarkDict();
extern void G__cpp_setup_memfuncmotherquarkDict();
extern void G__cpp_setup_funcmotherquarkDict();
extern void G__set_cpp_environmentmotherquarkDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "motherquark.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__motherquarkDictLN_TClass;
extern G__linked_taginfo G__motherquarkDictLN_TBuffer;
extern G__linked_taginfo G__motherquarkDictLN_TMemberInspector;
extern G__linked_taginfo G__motherquarkDictLN_TObject;
extern G__linked_taginfo G__motherquarkDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__motherquarkDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__motherquarkDictLN_motherquark;

/* STUB derived class for protected member access */
